        Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
        컴퓨터가 예기치 못한 상황이 발생했고 해결해달라 구문생성.

        단축키 " ctrl + alt + t "
        감싸기를 해야하는 코드를 나중에 인지했을때도 사용 가능.



        예외 발생구문을 try-catch로 처리(예외처리)

        -try{} :예외가 발생할 수 있을것 같은 코드들을 시도하는 구문

        -catch(예외){} :
                try 안에 작성한 코드들을 실행하는 도중 문제가 발생했고, 발생한 문제가 예상했던 문제와 같으면 내가 생각한 문제가 맞아!
                catch(잡아서) Catch{}중괄호 안에 작성된 구문 수행
                -> 발생된 예외를 다른 방식으로 처리했기 때문에, 프로그램이 멈추지 않고 정상적으로 수행
                catch는 여러게 작성 가능.

                문제발생이 예상되는데, 예상이 되지 않는경우
                catch(Exception e){} 로 작성하면 문제는 잡힘.



발생한 문제를 유연하게 처리할 것 try - catch